name: Build_Test

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:      
       server_type:  
        # Friendly description to be shown in the UI instead of 'name'
        description: 'server_type'
        # Default value if no value is explicitly provided
        default: 'server_type'
        # Input has to be provided for the workflow to run
        
       server_name:  
        # Friendly description to be shown in the UI instead of 'name'
        description: 'server_name'
        # Default value if no value is explicitly provided
        default: 'server_name'
        # Input has to be provided for the workflow to run
    
       interface:  
        # Friendly description to be shown in the UI instead of 'name'
        description: 'interface'
        # Default value if no value is explicitly provided
        default: 'interface'
        # Input has to be provided for the workflow to run
                

       package:  
        # Friendly description to be shown in the UI instead of 'name'
        description: 'package'
        # Default value if no value is explicitly provided
        default: 'package'
        # Input has to be provided for the workflow to run
        
#Setting environment variables

env:
  JAVA_HOME: ${java_home}
  SAG_HOME: ${sag_ci_home}
  SYS_PROPS: ${deployer_system_properties} 
        
jobs:
  Build_job:
    runs-on: ubuntu-latest

    steps:
      - name: Testing Code Checkout
        run: echo "Code Checkout"
      - uses: actions/checkout@v2

      - name: Run bash script
        shell: bash
        run: |
          chmod +x .github/scripts/test.sh
          param1=${{github.event.inputs.interface}}
          param2=${{github.event.inputs.package}}
          param3=$(date +"%Y-%m-%d %H:%M:%S")
          param4=4
          .github/scripts/test.sh "${param1}" "${param2}" "${param3}" "${param4}"
  
  Deploy_job:
    runs-on: ubuntu-latest
    needs: [Build_job]
    steps:
      - name: Testing Code Checkout
        run: echo "Code Checkout"
      - uses: actions/checkout@v2

      - name: Run bash script
        shell: bash
        run: |
          chmod +x .github/scripts/deploy_test.sh
          param1=${{github.event.inputs.interface}}
          param2=${{github.event.inputs.package}}
          param3=$(date +"%Y-%m-%d %H:%M:%S")
          param4=${{github.run_number}}
          param5=${{github.event.inputs.server_type}}
          param6=${{github.event.inputs.server_name}}
          .github/scripts/deploy_test.sh "${param1}" "${param2}" "${param3}" "${param4}" "${param5}" "${param6}"
