name: Build_Test

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:      
      interface:  
        # Friendly description to be shown in the UI instead of 'name'
        description: 'INTERFACE'
        # Default value if no value is explicitly provided
        default: 'INTERFACE'
        # Input has to be provided for the workflow to run
                

      package:  
        # Friendly description to be shown in the UI instead of 'name'
        description: 'PACKAGE'
        # Default value if no value is explicitly provided
        default: 'PACKAGE'
        # Input has to be provided for the workflow to run
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Testing Code Checkout
        run: echo "Code Checkout"
      - uses: actions/checkout@v2

      - name: Run bash script
        shell: bash
        run: |
          chmod +x .github/scripts/test.sh
          param1=${{github.event.inputs.interface}}
          param4=${{github.event.inputs.package}}
          param2=$(date +"%Y-%m-%d %H:%M:%S")
          param3=4
          .github/scripts/test.sh "${param1}" "${param2}" "${param3}" "${param4}"
