name: Webmethods POC

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
            
      choice:
        type: choice
        description: 'SERVER_TYPE'
        options: 
        - RT
        - BT
        - RT/BT
        # Input has to be provided for the workflow to run
        required: true 
      
      
      tags:  
        # Friendly description to be shown in the UI instead of 'name'
        description: 'SERVER_NAME'
        # Default value if no value is explicitly provided
        default: 'wmeasnad01xyz'
        # Input has to be provided for the workflow to run
        required: true

      choice1:  
        # Friendly description to be shown in the UI instead of 'name'
        type: choice
        description: 'INTEGRATION INTERFACE'
        # Default value if no value is explicitly provided
        options: 
        - INTERFACE-1
        - INTERFACE-2
        - INTERFACE-3
        # Input has to be provided for the workflow to run
        required: true
 

      choice2:  
        # Friendly description to be shown in the UI instead of 'name'
        type: choice
        description: 'PACKAGE NAME'
        # Default value if no value is explicitly provided
        options: 
        - PACKAGE-1
        - PACKAGE-2
        - PACKAGE-3
        # Input has to be provided for the workflow to run
        required: true
            
      choice3:  
        # Friendly description to be shown in the UI instead of 'name'
        type: choice
        description: 'STAGES'
        # Default value if no value is explicitly provided
        options: 
        - BUILD/DEPLOY
        - JUNIT
        - JMETER
        - ARTIFACTORY PUSH
        # Input has to be provided for the workflow to run
        required: true  
        
        
      tags1:  
        # Friendly description to be shown in the UI instead of 'name'
        description: 'UT_USER'
        # Default value if no value is explicitly provided
        default: 'USERNAME'
        # Input has to be provided for the workflow to run
                

      tags2:  
        # Friendly description to be shown in the UI instead of 'name'
        description: 'UT_PASSWORD'
        # Default value if no value is explicitly provided
        default: 'PASSWORD'
        # Input has to be provided for the workflow to run
           

jobs:
     
  trigger-test: #Testing conditions
     name: Testing conditions
     runs-on: ubuntu-latest
     if: |
      inputs.choice == 'RT' &&
      (
        inputs.choice1 == 'INTERFACE-1' && 
        inputs.choice2 == 'PACKAGE-1' 
      )
      steps:
      -name: testing conditions
       uses: actions/checkout@v2
       run: echo "testing conditions"
     
