name: input_parameter_workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
            
      choice1:
        type: choice
        description: 'SERVER_TYPE'
        options: 
        - RT
        - BT
        - RT/BT
        # Input has to be provided for the workflow to run
        required: true 
        default: true

      choice2:
        type: choice
        description: 'SERVER_RT_NAME'
        options: 
        - RT1
        - RT2
        # Input has to be provided for the workflow to run
        required: true


env:
  DAY_OF_WEEK: Monday     
  RT_Server: RT
  BT_Server: BT

jobs:  
       
           
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
          
      - name: "Testing Environment Variables"
        if: ${{ env.RT_Server == 'RT' }}
        run: echo "RT Server is selected"      
        
      - name: "Testing Conditions"
        if: ${{ github.event.inputs.choice == 'BT' && github.event.inputs.choice2 == 'RT2'}}
        run: echo "BT Server and RT2 is selected" 

  validate: #Perform validation before any other jobs run.  If we fail validation, don't run anything else.
    name: Validation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate test
      run: .github/scripts/test.sh
      
  


