# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.

# This is a basic workflow that is manually triggered


# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'SERVER_TYPE'
        # Default value if no value is explicitly provided
        default: 'RT/BT'
        # Input has to be provided for the workflow to run
        required: true
        
      tags:  
        # Friendly description to be shown in the UI instead of 'name'
        description: 'SERVER_NAME'
        # Default value if no value is explicitly provided
        default: 'wmeasnad01xyz'
        # Input has to be provided for the workflow to run
        required: true
        
      choice:  
        # Friendly description to be shown in the UI instead of 'name'
        type: choice
        description: 'STAGES'
        # Default value if no value is explicitly provided
        options: 
        - BUILD/DEPLOY
        - JUNIT
        - JMETER
        # Input has to be provided for the workflow to run
        required: true  
      
#       choice:
#       description: Make a choice
#       options:
#       - integration
#       - integration2
#       - integration3
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greetjob1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
      
  job2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: testing
      run: echo hello world
    
