name: Mixed inputs

on:
   workflow_dispatch

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"

  Job1_Prepare:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
  
  job2_Build:
    runs-on: ubuntu-latest
    needs: [Job1_Prepare]
    steps:
      - run: echo ${{needs.job1_Prepare.outputs.output1}} ${{needs.job1_Prepare.outputs.output2}}   
            
  job3_Deploy:
    runs-on: ubuntu-latest
    needs: [job2_Build]
    steps:
      - run: echo ${{needs.job1_Build.outputs.output1}} ${{needs.job1_Build.outputs.output2}}    
