name: Test_Runner

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
            


      tags:  
        #Friendly description to be shown in the UI instead of 'name'
        description: 'SERVER_NAME'
        # Default value if no value is explicitly provided
        default: 'wmeasnad01xyz'
        # Input has to be provided for the workflow to run
        required: true



jobs:  
       
           
  greeting_job:
    runs-on: ubuntu-latest

    steps:
   
        
      - name: "Testing Conditions"
        if:  ${{github.event.inputs.choice == 'BT' }}
        run: echo "BT Server is selected"

      
  
