name: Webmethods POC

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
            
      choice:
        type: choice
        description: 'SERVER_TYPE'
        options: 
        - RT
        - BT
        - RT/BT
        # Input has to be provided for the workflow to run
        required: true 
      
      
      tags:  
        # Friendly description to be shown in the UI instead of 'name'
        description: 'SERVER_NAME'
        # Default value if no value is explicitly provided
        default: 'wmeasnad01xyz'
        # Input has to be provided for the workflow to run
        required: true
      
            
      choice1:  
        # Friendly description to be shown in the UI instead of 'name'
        type: choice
        description: 'STAGES'
        # Default value if no value is explicitly provided
        options: 
        - BUILD/DEPLOY
        - JUNIT
        - JMETER
        # Input has to be provided for the workflow to run
        required: true  

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Webemthods POC
      run: echo "Hello ${{ github.event.inputs.name }}"

  Job1_Prepare:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::Job1_Prepare"
      - id: step2
        run: echo "::set-output name=test::Job1_Prepare"
  
  job2_Build:
    runs-on: ubuntu-latest
    needs: [Job1_Prepare]
    steps:
      - run: echo ${{needs.job1_Prepare.outputs.output1}} ${{needs.job1_Prepare.outputs.output2}}   
            
  job3_Deploy:
    runs-on: ubuntu-latest
    needs: [job2_Build]
    steps:
      - run: echo ${{needs.job1_Build.outputs.output1}} ${{needs.job1_Build.outputs.output2}}
      
  job4_Junit:
    runs-on: ubuntu-latest
    needs: [job3_Deploy]
    steps:
      - run: echo ${{needs.job1_Build.outputs.output1}} ${{needs.job1_Build.outputs.output2}}  
      
  job5_JMeter:
    runs-on: ubuntu-latest
    needs: [job4_Junit]
    steps:
      - run: echo ${{needs.job1_Build.outputs.output1}} ${{needs.job1_Build.outputs.output2}}   
      
  job6_Declarative_post_actions:
    runs-on: ubuntu-latest
    needs: [job5_JMeter]
    steps:
      - name: Run a one-line script
        run: echo "job5_JMeter ${{gtihub.event.input.tags}}"
